### ISSUE TITLE
No installation guidelines provided in the readme

### ISSUE THREAD

**Issue by Gerriko** [SiliconLabs/application_examples#7]
I note that in your "peripheral_examples" repository you provide install instruction (step 4: This repo, cloned to... under the requirements section). Nothing is provided here in the readme.

**Comment by ghost** [comment]
Hi @Gerriko,

For repositories under application_examples, see each specific project readme file for instructions on how to setup the project.  In some cases the instructions explain how to start with an existing SDK example and copy in source files.  In other cases, you would import the project file in a manner similar to the peripheral_examples repository.

We are in the process of consolidating project file formats and install methods to make the user experience more consistent.

Best regards,
Chris
